services:
  server:
    image: movies-tmdb-backend:latest
    ports:
      - 3010:3010
    build:
      context: ./backend
  web:
    image: movies-tmdb-frontend:latest
    ports:
      - 5173:80
    build:
      context: ./frontend
